In [1]:
# Employee Project Analysis using pandas and numpy
#This project performs data cleaning,transformation and analysis

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Task 1 : Create employee,project,and seniority dataframes
employee = pd.DataFrame({'ID':['A001','A002','A003','A004','A005'],
                         'Name':['John Cruise','Alice Luxemburg','Tom Cruise','Nina Agara','Amy Johny'],
                         'Gender':['M','F','M','F','F'],
                         'City':['Paris','London','Berlin','Newyork','Madrid'],
                         'Age':[25,27,29,31,30]})
project = pd.DataFrame({'ID':['A001','A002','A003','A004','A005','A002','A005','A003','A001','A003','A001','A004','A004','A005'],
                        'Project':['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8','Project 9',
                                   'Project 10','Project 11','Project 12','Project 13','Project 14'],
                        'Cost':[1002000,2000000,4500000,5500000,np.nan,68000,400000,350000,300000,2000000,np.nan,3000000,3000000,2000000],
                        'Status':['Finished','Ongoing','Finished','Ongoing','Finished','Failed','Finished','Failed','Ongoing','Finished','Failed',
                                  'Ongoing','Finished','Finished']})
seniority = pd.DataFrame({'ID':['A001','A002','A003','A004','A005'],
                          'Designation_level':[2,2,3,2,3]})

# Save the datsaframes as CSV files
employee.to_csv("employee.csv",index=False)
project.to_csv("project.csv",index=False)
seniority.to_csv("seniority.csv",index=False)

In [4]:
employee_df=pd.read_csv("employee.csv")
project_df=pd.read_csv("project.csv")
seniority_df=pd.read_csv("seniority.csv")

employee_df.head()

     ID             Name Gender     City  Age
0  A001      John Cruise      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003       Tom Cruise      M   Berlin   29
3  A004       Nina Agara      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6    68000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9   300000.0   Ongoing
9   A003  Project 10  2000000.0  Finished
10  A001  Project 11        NaN    Failed
11  A004  Project 12  3000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14  2000000.0  Finished

In [6]:
seniority_df

     ID  Designation_level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [7]:
# Task 2:(Replace missing cost values with running average)
# Initialize variables to keep track of total cost and count
running_total=0
count=0

# Loop through each row in the dataframe
for i in range(len(project_df)):

#Get the current cost value
    cost=project_df.loc[i,'Cost']

# Check if the cost is not missing
    if pd.notna(cost):
        running_total+=cost
        count+=1
# if the value is missing replace it with running average
    else:
         project_df.loc[i,'Cost']=running_total/count

# Display numbers without scientific notation
pd.options.display.float_format='{:.0f}'.format
print(project_df)

      ID     Project    Cost    Status
0   A001   Project 1 1002000  Finished
1   A002   Project 2 2000000   Ongoing
2   A003   Project 3 4500000  Finished
3   A004   Project 4 5500000   Ongoing
4   A005   Project 5 3250500  Finished
5   A002   Project 6   68000    Failed
6   A005   Project 7  400000  Finished
7   A003   Project 8  350000    Failed
8   A001   Project 9  300000   Ongoing
9   A003  Project 10 2000000  Finished
10  A001  Project 11 1791111    Failed
11  A004  Project 12 3000000   Ongoing
12  A004  Project 13 3000000  Finished
13  A005  Project 14 2000000  Finished

In [8]:
#Task 3: 
#Split 'Name'column into 'first_name' and 'last_name'
employee_df[['First_name','Last_name']]=employee_df['Name'].str.split(' ',expand=True)
# Remove the original 'Name' column
employee_df.drop('Name',axis=1,inplace=True)

employee_df

     ID Gender     City  Age First_name  Last_name
0  A001      M    Paris   25       John     Cruise
1  A002      F   London   27      Alice  Luxemburg
2  A003      M   Berlin   29        Tom     Cruise
3  A004      F  Newyork   31       Nina      Agara
4  A005      F   Madrid   30        Amy      Johny

In [9]:
#Task 4:
# Merge employee,seniority,and project dataframes 
# Using 'ID' as the common key
Final=employee_df.merge(seniority_df,on='ID').merge(project_df,on='ID')

print(Final)

      ID Gender     City  Age First_name  Last_name  Designation_level  \
0   A001      M    Paris   25       John     Cruise                  2
1   A001      M    Paris   25       John     Cruise                  2
2   A001      M    Paris   25       John     Cruise                  2
3   A002      F   London   27      Alice  Luxemburg                  2
4   A002      F   London   27      Alice  Luxemburg                  2
5   A003      M   Berlin   29        Tom     Cruise                  3
6   A003      M   Berlin   29        Tom     Cruise                  3
7   A003      M   Berlin   29        Tom     Cruise                  3
8   A004      F  Newyork   31       Nina      Agara                  2
9   A004      F  Newyork   31       Nina      Agara                  2
10  A004      F  Newyork   31       Nina      Agara                  2
11  A005      F   Madrid   30        Amy      Johny                  3
12  A005      F   Madrid   30        Amy      Johny                  3
13  A005      F   Madrid   30        Amy      Johny                  3

       Project    Cost    Status
0    Project 1 1002000  Finished
1    Project 9  300000   Ongoing
2   Project 11 1791111    Failed
3    Project 2 2000000   Ongoing
4    Project 6   68000    Failed
5    Project 3 4500000  Finished
6    Project 8  350000    Failed
7   Project 10 2000000  Finished
8    Project 4 5500000   Ongoing
9   Project 12 3000000   Ongoing
10  Project 13 3000000  Finished
11   Project 5 3250500  Finished
12   Project 7  400000  Finished
13  Project 14 2000000  Finished

In [10]:
#Task 5
# Assign 5% bonus only if project status is 'Finished'
# np.where condition applies bonus
Final['Bonus']=np.where(Final['Status']=='Finished',Final['Cost']*0.05,0)

print(Final[['ID','Project','Status','Bonus']])

      ID     Project    Status  Bonus
0   A001   Project 1  Finished  50100
1   A001   Project 9   Ongoing      0
2   A001  Project 11    Failed      0
3   A002   Project 2   Ongoing      0
4   A002   Project 6    Failed      0
5   A003   Project 3  Finished 225000
6   A003   Project 8    Failed      0
7   A003  Project 10  Finished 100000
8   A004   Project 4   Ongoing      0
9   A004  Project 12   Ongoing      0
10  A004  Project 13  Finished 150000
11  A005   Project 5  Finished 162525
12  A005   Project 7  Finished  20000
13  A005  Project 14  Finished 100000

In [11]:
# Task 6(Demote designation level by 1 for failed projects)
# Demote(increase level number)
Final.loc[Final['Status']=='Failed','Designation_level']+=1
# Remove employees with level > 4
Final=Final[Final['Designation_level']<=4]

print(Final[['ID','Project','Status','Designation_level']])

      ID     Project    Status  Designation_level
0   A001   Project 1  Finished                  2
1   A001   Project 9   Ongoing                  2
2   A001  Project 11    Failed                  3
3   A002   Project 2   Ongoing                  2
4   A002   Project 6    Failed                  3
5   A003   Project 3  Finished                  3
6   A003   Project 8    Failed                  4
7   A003  Project 10  Finished                  3
8   A004   Project 4   Ongoing                  2
9   A004  Project 12   Ongoing                  2
10  A004  Project 13  Finished                  2
11  A005   Project 5  Finished                  3
12  A005   Project 7  Finished                  3
13  A005  Project 14  Finished                  3

In [12]:
#Task 7:
# Add title(Mr./Mrs.) to first_name based on gender
Final['First_name']=np.where(Final['Gender']=='M',
                          'Mr. '+Final['First_name'],
                          'Mrs. '+ Final['First_name'])
# And drop gender column
Final.drop('Gender',axis=1,inplace=True)
print(Final[['ID','First_name']])

      ID  First_name
0   A001    Mr. John
1   A001    Mr. John
2   A001    Mr. John
3   A002  Mrs. Alice
4   A002  Mrs. Alice
5   A003     Mr. Tom
6   A003     Mr. Tom
7   A003     Mr. Tom
8   A004   Mrs. Nina
9   A004   Mrs. Nina
10  A004   Mrs. Nina
11  A005    Mrs. Amy
12  A005    Mrs. Amy
13  A005    Mrs. Amy

In [13]:
# Task 8(Promote designation level by 1 if age>29)
for i in range(len(Final)):
# Check if age is greater than 29
    if Final.loc[i,'Age']>29:
# Promote( decrease designation level since 1 is the highest)        
        Final.loc[i,'Designation_level']-=1
# Ensure designation level does not go below 1        
Final['Designation_level']=Final['Designation_level'].clip(lower=1)

print(Final[['ID','Age','Designation_level']])

      ID  Age  Designation_level
0   A001   25                  2
1   A001   25                  2
2   A001   25                  3
3   A002   27                  2
4   A002   27                  3
5   A003   29                  3
6   A003   29                  4
7   A003   29                  3
8   A004   31                  1
9   A004   31                  1
10  A004   31                  1
11  A005   30                  2
12  A005   30                  2
13  A005   30                  2

In [14]:
#Task 9:
# Calculate total project cost for each employee using groupby
Total_project_cost=Final.groupby(['ID','First_name']) ['Cost'].sum().reset_index()
# Renaming columns for better readability
Total_project_cost.rename(columns={'Cost' :'Totalcost'},inplace=True)

print(Total_project_cost)

     ID  First_name  Totalcost
0  A001    Mr. John    3093111
1  A002  Mrs. Alice    2068000
2  A003     Mr. Tom    6850000
3  A004   Mrs. Nina   11500000
4  A005    Mrs. Amy    5650500

In [15]:
#Task 10 
# Filter employees whose city contains the letter 'o'
o_city=Final[Final['City'].str.contains('o', case=False)]

print(o_city[['ID','First_name','Last_name','City','Age']])

      ID  First_name  Last_name     City  Age
3   A002  Mrs. Alice  Luxemburg   London   27
4   A002  Mrs. Alice  Luxemburg   London   27
8   A004   Mrs. Nina      Agara  Newyork   31
9   A004   Mrs. Nina      Agara  Newyork   31
10  A004   Mrs. Nina      Agara  Newyork   31